# Week:1 Introduction to Data Mining

### Objective:
The objective of the assignment is to understand how to install libraries, creating variables, calculate statistical metrics, basic python opreations, creating dataframes and basic pandas operations on the dataframe.

We have to use Fatal Police Shooting Data to answer the questions given in this notebook.

### Fatal Police Shooting Data

**About dataset**\
The dataset consists of following columns
1. **id**                         : unqiue identifier of each victim
2. **name**                       : name of a victim
3. **date**                       : date on fatal shooting 
4. **manner_of_death**            : manner of death classification
    * Shot
    * Shot and Tasered
5. **armed**                      : indicates that the victim was armed with some sort of implement that a police officer believed could inflict harm
    * undetermined: it is not known whether or not the victim had a weapon
    * unknown: the victim was armed, but it is not known what the object was
    * unarmed: the victim was not armed
6. **age**                        : age of victim
7. **gender**                     : the gender of the victim. The Post identifies victims by the gender they identify with if reports indicate that it differs from their biological sex.
    * M: Male
    * F: Female
    * None: Unknown
8. **race**                       : race of victim
    * W: White, non-Hispanic
    * B: Black, non-Hispanic
    * A: Asian
    * N: Native American
    * H: Hispanic
    * O: Other
    * None: unknown
9. **city**                       : the city where the fatal shooting took place. Note that in some cases this field may contain a county name if a more specific city is unavailable or unknown.
10. **state**                     : two-letter postal code abbreviation
11. **signs_of_mental_illness**   : News reports have indicated the victim had a history of mental health issues, expressed suicidal intentions or was experiencing mental distress at the time of the shooting.
12. **threat_level**              : These would include incidents where officers or others were shot at, threatened with a gun, attacked with other weapons or physical force, etc. The attack category is meant to flag the highest level of threat. The other and undetermined categories represent all remaining cases. Other includes many incidents where officers or others faced significant threats. 
13. **flee**                      : News reports have indicated the victim was moving away from officers
    * Foot
    * Car
    * Not fleeing
14. **body_camera**               : News reports have indicated an officer was wearing a body camera and it may have recorded some portion of the incident.

## Let's Begin

### Question: 1            (2 Marks)                                                                                                                                                  

Install the required libraries for the assignment

In [160]:
import numpy as np

In [161]:
# Install a libray which help us to data injecting, data manipulation on the dataframe
!pip install "pandas"

Looking in indexes: https://nexus.corp.indeed.com/repository/pypi/simple
Requirement already satisfied: pandas in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (2.1.0)
Requirement already satisfied: tzdata>=2022.1 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.22.4 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2022.7)
Requirement already satisfied: six>=1.5 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [162]:
# Import the libary
import pandas as pd

#Check the version
print(pd.__version__)

2.1.0

In [163]:
# Upgrade the installed library to the latest version
!pip install --upgrade "pandas" --user

Looking in indexes: https://nexus.corp.indeed.com/repository/pypi/simple
Requirement already satisfied: pandas in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (2.1.0)
Requirement already satisfied: pytz>=2020.1 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.22.4 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (1.23.5)
Requirement already satisfied: tzdata>=2022.1 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/slakshmanan/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [164]:
# Check the latest version after upgrading library
import pandas as pd
print(pd.__version__)

 #Todo: Code to fill
 # 1. '<<__A__>>'--> import requried libraries
 # 2. '<<__B__>>'--> Check the version 
 # 3. '<<__C__>>'--> Updgrade the installed library to leatest version
 # 4. '<<__D__>>'--> Check the latest version after upgrading library

2.1.0

### Question: 2 (2 marks)

- Fill in the missing code. 
- Store the data in to a variable, then display the top 5 and bottom 5 rows of records and check the dataset's shape.

In [165]:
# Load the dataframe and store it into the variable
df = pd.read_csv('fatal-police-shootings-data.csv')

In [166]:
# Display the Top 5 records
df.head(5)

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False

In [167]:
# Display the last 5 records
df.tail(5)

 #Todo: Code to fill
 # 1. '<<__A__>>'--> Appropriate pandas function to read the file
 # 2. '<<__B__>>'--> Appropriate path of the csv file
 # 3. '<<__C__>>'--> Check for top 5 records using appropriate function
 # 4. '<<__D__>>'--> Check for bottom 5 records using appropriate function

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
4473,4907,Connor Betts,2019-08-04,shot,gun,24.0,M,W,Dayton,OH,True,attack,Not fleeing,False
4474,4909,Robert Clay Wilsford Jr.,2019-08-04,shot,gun,65.0,M,NaN,Hanceville,AL,True,attack,Not fleeing,False
4475,4910,TK TK,2019-08-05,shot,undetermined,NaN,NaN,NaN,Salt Lake City,UT,False,undetermined,Not fleeing,True
4476,4914,James Kirkwood,2019-08-05,shot,knife,49.0,M,B,Memphis,TN,False,attack,Foot,False
4477,4916,Marvin Alexis Urbina,2019-08-05,shot,vehicle,19.0,M,H,Bakersfield,CA,False,other,Car,False

In [168]:
# Check the shape of the datset
print("No of columns: ",df.shape[1])
print("No of rows: ",df.shape[0])

No of columns:  14
No of rows:  4478

### Question: 3 (2 marks)
Caluculate the statistical metrics of a column in a dataset

In [169]:
# Calculate the standard devaition
df['age'].std()

13.067598403906874

In [170]:
# Average age of a victim
df['age'].mean()

36.87932234857276

In [171]:
# Which city records the most Kill Events by police?
df['count'] = df[['city', 'id']].groupby(['city']).transform('count')
# two cities have the same count, but outputting just one
df[['city', 'count']].sort_values('count', ascending=False).head(1)

             city  count
1246  Los Angeles     68

### Question: 4 (2 marks)
Create a new  " age categories " column using age column of a dataset

In [172]:
'''Hint: if age is between 0 to 12, then categorise as child. 
13-21 as Teenage, 22-34 as Youth, 35-50 as Adult, 51-120 as Senior citizens'''

    #-------- build the code down --------#
col = 'age'
ranges = [(df[col] > 50) & (df[col] <= 120), (df[col] > 34) & (df[col] <= 50), (df[col] > 21) & (df[col] <= 34), (df[col] > 12) & (df[col] <= 21), (df[col] >= 0) & (df[col] <= 12)]
cats = ['Senior citizens', 'Adult', 'Youth', 'Teenage', 'Child']
age_cat = np.select(ranges, cats, default=np.nan)

In [173]:
df['age_categories'] =  age_cat

In [174]:
# Display the first 5 records after creating the column
df.head(5)

#Todo: Code to fill
 # 1. Write code to build the conditions for the categories of age
 # 2. '<<__A__>>'--> method to display first 5 rows

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,count,age_categories
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,1,Senior citizens
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,2,Adult
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,9,Youth
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,15,Youth
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,2,Adult

### Question: 5 (2 marks)
Find the state which records the most kill events by police and display the type of attacks done on the male senior citizen of that state.

In [175]:
# Which State records the most Kill Events by police?
df.loc[df[['state', 'id']].groupby(['state']).count().max()]['state']

680    CA
Name: state, dtype: object

In [176]:
# What kinds of attacks (armed) are most affected by the male senior citizens in the state of 'CA'
df[(df['age_categories'] == 'Senior citizens') & (df['gender'] =="M") &  (df['state'] == 'CA')]['armed'].drop_duplicates()

#Todo: Code to fill

# 1. '<<__A__>>'--> write proper age category 
# 2. '<<__B__>>'--> write state filter 
# 3. '<<__C__>>'--> write the appropriate command to show distinct attacks without repetitions

89                 gun
285         toy weapon
468              knife
576       undetermined
651         box cutter
791                NaN
1907           unarmed
2104    unknown weapon
2158              pipe
2492      blunt object
2782         pitchfork
3406        metal pipe
Name: armed, dtype: object

In [177]:
# Save the processed data to use for Week2 assignment 
df.to_csv("week_1_assignment_output.csv",index=False)

## Thank you!